#!/usr/bin/env python3

import sys
import os
import operator
import itertools
import argparse

import fast5_reader

def process_file(fn, st):
    try:
        f = fast5_reader.File(fn)
        if not f.have_fastq(st):
            print(fn + ': no fastq for strand ' + str(st), file=sys.stderr)
            return
        fq = f.get_fastq(st)
        f.close()
        print(fq.strip())
    except:
        print(fn + ': error processing file', file=sys.stderr)

if __name__ == "__main__":
    description = """
    Extract 2D Fastq from Fast5 file.
    """
    parser = argparse.ArgumentParser(description=description, epilog='')
    parser.add_argument('--strand', action='store', type=int, default=0, help='Strand (2 for 2D)')
    parser.add_argument('--fofn', help='File of Fast5 files')
    parser.add_argument('input', action='store', help='Fast5 file')
    args = parser.parse_args()

    if args.input:
        process_file(args.input, args.strand)
    if args.fofn:
        fofn_f = open(args.fofn)
        for line in fofn_f:
            process_file(line.strip(), args.strand)
        fofn_f.close()
