#!/usr/bin/env python3

import sys
import os
import operator
import itertools
import argparse

import fast5_reader

description = """
Extract 2D Fastq from Fast5 file.
"""
parser = argparse.ArgumentParser(description=description, epilog='')
parser.add_argument('--strand', action='store', type=int, default=0, help='Strand (2 for 2D)')
parser.add_argument('input', action='store', help='Fast5 file')
args = parser.parse_args()

fn = args.input
strand = args.strand

try:
    f = fast5_reader.File(fn)
except OSError:
    print(fn + ': could not open file', file=sys.stderr)
    sys.exit(1)

if not f.have_fastq(strand):
    print(fn + ': no fastq for strand ' + str(strand), file=sys.stderr)
    sys.exit(1)

fq = f.get_fastq(strand)
f.close()
print(fq.strip())
