#!/usr/bin/env python3

import sys
import os
import operator
import itertools
import argparse

import fast5_reader

def process_file(fn, st, bc_grp):
    try:
        f = fast5_reader.File(fn)
        if not f.have_fastq(st, basecall_group=bc_grp):
            print(fn + ': no fastq for strand ' + str(st) + ' in group ' + str(bc_grp), file=sys.stderr)
            return
        fq = f.get_fastq(st, basecall_group=bc_grp)
        f.close()
        print(fq, end='')
    except:
        print(fn + ': error processing file', file=sys.stderr)

if __name__ == "__main__":
    description = """
    Extract 2D Fastq from Fast5 file.
    """
    parser = argparse.ArgumentParser(description=description, epilog='')
    parser.add_argument('--strand', type=int, default=0, help='Strand (2 for 2D)')
    parser.add_argument('--fofn', help='File of Fast5 files')
    parser.add_argument('--rnn', help='Use RNN basecalls', action='store_true', default=False)
    parser.add_argument('input', nargs='?', help='Fast5 file')
    args = parser.parse_args()

    bc_grp = ['metrichor_hmm', 'metrichor_rnn'][args.rnn]
    if args.input:
        process_file(args.input, args.strand, bc_grp)
    if args.fofn:
        fofn_f = open(args.fofn)
        for line in fofn_f:
            process_file(line.strip(), args.strand, bc_grp)
        fofn_f.close()
