#!/usr/bin/env python3

import argparse
import sys

import h5py
import numpy as np

if __name__ == "__main__" and "__file__" in globals():
    description = """
    Extract dataset&attributes from HDF5 file.
    """
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('path', action='store', help='HDF5 path')
    parser.add_argument('file', action='store', help='HDF5 file')
    args = parser.parse_args()

    f = h5py.File(args.file)
    a = f[args.path]
    if len(a.shape) > 0:
        dt = np.dtype([t if 'S' not in t[1] else (t[0], t[1].replace('S', 'U'))
                       for t in a.dtype.descr])
        d = dict(a.attrs)
        for k in d.keys():
            print('#' + k + '\t' + str(d[k]))
        print('\t'.join(dt.names))
        for e in a[()].astype(dt):
            print('\t'.join((str(v) for v in e)))
    else:
        print(str(a[()].decode()), end='')
