#!/usr/bin/env python3

import numpy as np
import operator
import sys

highlights = {"n_wrong": 0, "n_errors_per_called_base": 0, "total_kbp_per_ch": 1}
best_index = dict()
d = np.genfromtxt(sys.stdin.buffer, dtype=None, names=True)
for k in highlights.keys():
    if highlights[k] == 0:
        best_index[k], _ = min(enumerate(d[k]), key=operator.itemgetter(1))
    else:
        best_index[k], _ = max(enumerate(d[k]), key=operator.itemgetter(1))
for i in range(len(d)):
    l = list()
    for key in d.dtype.names:
        if type(d[i][key]) == np.bytes_:
            val = d[i][key].decode()
        else:
            val = d[i][key]
        if key not in highlights.keys() or i != best_index[key]:
            l.append(str(val))
        else:
            l.append("\\textbf{" + str(val) + "}")
    print("\t".join(l))
