#!/bin/bash
source "$(dirname "$(readlink -e "${BASH_SOURCE[0]}")")"/common.sh

printab "nanocall_tag" "aln" "aln_tag" "m1d_wrong" "n_wrong" "both_wrong"
for f in "$@"; do
    tag=${f#*metrichor+nanocall~}
    nanocall_tag=${tag%%.*}
    tag=${tag#*.}
    aln=${tag%%~*}
    tag=${tag#*~}
    aln_tag=${tag%%.*}
    num_reads=$(tail -n+2 ${f} | wc -l)
    num_reads_m_mis=$(tail -n+2 ${f} | awk -F '\t' '$2==0 && !($3==0 && $4==0)' | wc -l)
    num_reads_n_mis=$(tail -n+2 ${f} | awk -F '\t' '$2==0 && !($5==0 && $6==0)' | wc -l)
    num_reads_both_mis=$(tail -n+2 ${f} | awk -F '\t' '$2==0 && !($3==0 && $4==0) && !($5==0 && $6==0)' | wc -l)
    printab ${nanocall_tag} ${aln} ${aln_tag} \
        $(echo "scale=3; $num_reads_m_mis / $num_reads" | bc) \
        $(echo "scale=3; $num_reads_n_mis / $num_reads" | bc) \
        $(echo "scale=3; $num_reads_both_mis / $num_reads" | bc)
done |
sort -k 5n
